FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /usr/src/app


FROM base AS build
RUN corepack enable
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run -r build:admin


FROM base AS server
WORKDIR /prod/admin
COPY --from=build /usr/src/app/apps/admin/.next/standalone ./.next/standalone
COPY --from=build /usr/src/app/apps/admin/.next/static ./.next/standalone/apps/admin/.next/static
COPY --from=build /usr/src/app/apps/admin/public ./.next/standalone/apps/admin/public
EXPOSE 3000
ENV NODE_ENV=production
ENV HOST=0.0.0.0
CMD [ "node", ".next/standalone/apps/admin/server.js" ]
